services:
  - type: web
    name: car-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: car-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: car-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: car-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: car-postgres
          property: user
      - key: DB_PASS
        fromDatabase:
          name: car-postgres
          property: password
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_JWT_EXPIRATION_MS
        value: "86400000"
      - key: APP_CORS_ALLOWED_ORIGIN_PATTERNS
        value: "https://*.onrender.com"

databases:
  - name: car-postgres
    plan: free

